site_name: py-site
site_url: https://enifl33fi.github.io/py-site/
repo_url: https://github.com/enifl33fi/py-site
edit_uri: edit/main/docs/

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true

plugins:
  - search:
      lang: ru
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js