site_name: py-site
repo_url: https://github.com/enifl33fi/py-site
edit_uri: edit/master/docs/

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Главная: index.md
  - T1. Сравнение SSG: t1.md
  - P4. Развёртывание на Helios: p4.md

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true

plugins:
  - search:
      lang: ru
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

extra_javascript:
  - assets/mathjax/config.js
  - assets/mathjax/tex-mml-chtml.js